import { StyleSheet } from "react-native";
import fonts from '../../constants/fonts'

const styles=StyleSheet.create({
    appLogo:{
        height:135,
        width:135,
        alignSelf:"center"
    },
    mainView:{
        flex:1,
        backgroundColor:"#fff",
        flexDirection:"column"
    },
    subView1:{
        flex:3,
        justifyContent:"flex-end",
    },
    subView2:{
        flex:1,
        justifyContent:"flex-end",
    },
    headingText1:{
        fontSize:32,
        textAlign:"center",
        fontFamily:fonts.SfPro_Semibold,
        marginTop:15,
        color:"#04253F"
    },
    headingText2:{
        fontSize:32,
        textAlign:"center",
        fontFamily:fonts.SfPro_Semibold,
        marginTop:2,
        color:"#04253F"
    },
    normalText1:{
        fontFamily:fonts.SfPro_Regular,
        fontSize:16,
        textAlign:"center",
        marginTop:10,
        color:"#414C55"
    },
    normalText2:{
        fontFamily:fonts.SfPro_Regular,
        fontSize:16,
        textAlign:"center",
        marginTop:5,
        color:"#414C55",
        marginBottom:90
    },
    buttonView:{
        height:55,
        width:'90%',
        marginLeft:'5%',
        backgroundColor:"#1084DC",
        justifyContent:"center",
        alignItems:"center",
        borderRadius:6
    },
    buttonText:{
        color:"#FFFFFF",
        fontSize:18,
        fontFamily:fonts.SfPro_Semibold
    },
    accountView:{
        flexDirection:"row",
        alignSelf:"center",
        marginTop:30,
        marginBottom:50
    },
    accountText:{
        fontFamily:fonts.SfPro_Regular,
        fontSize:16,
        color:"#04253F"
    },
    loginText:{
        color:"#1084DC",
        textDecorationLine:"underline",
        fontSize:16,
        fontFamily:fonts.SfPro_Semibold
    }
})

export default styles; 