export default images = {
  dubmle: require("../assets/images/Dumble1.png"),
  bottom: require("../assets/images/bottom.png"),
  eventnew1: require("../assets/images/eventnew1.png"),
  fire1: require("../assets/images/fire1.png"),
  Flashnw1: require("../assets/images/Flashnw1.png"),
  image1: require("../assets/images/image1.png"),
  gymicon1: require("../assets/images/gymicon1.png"),
  heart1: require("../assets/images/heart1.png"),
  map: require("../assets/images/map.png"),
  image2: require("../assets/images/image2.png"),
  back: require("../assets/images/back.png"),
  mapimg: require("../assets/images/map-img.png"),
  add: require("../assets/images/plus.png"),
  search: require("../assets/images/search.png"),
  search1:require("../assets/images/Magnifer1.png"),
  user: require("../assets/images/user.png"),
  group: require("../assets/images/group1.png"),
  mic: require("../assets/images/mic.png"),
  location3: require("../assets/images/location-pin.png"),
  location5: require("../assets/images/location5.png"),
  time1: require("../assets/images/time1.png"),
  time: require("../assets/images/time.png"),
  facebook: require("../assets/images/facebook.png"),
  apple: require("../assets/images/apple.png"),
  onboarding1: require("../assets/images/image3.png"),
  onboarding2: require("../assets/images/image4.png"),
  onboarding3: require("../assets/images/image5.png"),
  walkthrough1: require("../assets/images/walkthrough1.png"),
  walkthrough2: require("../assets/images/walkthrough2.png"),
  walkthrough3: require("../assets/images/walkthrough3.png"),
  next: require("../assets/images/next.png"),
  home: require("../assets/images/home.png"),
  map: require("../assets/images/map1.png"),
  profile: require("../assets/images/profile.png"),
  profile4: require("../assets/images/profile3.png"),
  profile5: require("../assets/images/profile4.png"),
  profile_image: require("../assets/images/profile1.png"),
  home_active: require("../assets/images/home-active.png"),
  map_active: require("../assets/images/map-active.png"),
  map2: require("../assets/images/Map2.png"),
  map3: require("../assets/images/Map3.png"),
  profile_active: require("../assets/images/profile-active.png"),
  logo: require("../assets/images/Logo1.png"),
  cofit: require("../assets/images/cofit.png"),
  cofitLogo: require("../assets/images/Cofit-logo.png"),
  google: require("../assets/images/google-icon.png"),
  skip: require("../assets/images/skip.png"),
  location: require("../assets/images/Vector.png"),
  filter: require("../assets/images/filter.png"),
  search: require("../assets/images/search.png"),
  event1: require("../assets/images/event1.png"),
  event2: require("../assets/images/event2.png"),
  car: require("../assets/images/car.png"),
  share: require("../assets/images/share.png"),
  country: require("../assets/images/country.png"),
  logout: require("../assets/images/logout.png"),
  backimg: require("../assets/images/backimg.png"),
  groupbg: require("../assets/images/GroupBg.png"),
  clock: require("../assets/images/clock.png"),
  calendar: require("../assets/images/Calendar.png"),
  location1: require("../assets/images/location.png"),
  camera: require("../assets/images/camera.png"),
  close: require("../assets/images/close.png"),
  myEvents: require("../assets/images/myEvents.png"),
  home1: require("../assets/images/home1.png"),
  home2: require("../assets/images/home2.png"),
  home3: require("../assets/images/home3.png"),
  home4: require("../assets/images/Home4.png"),
  home5: require("../assets/images/Home5.png"),
  pin: require("../assets/images/pin2.png"),
  pen: require("../assets/images/pen.png"),
  pen3: require("../assets/images/pen3.png"),
  adaptiveIcon: require("../assets/images/adaptive-icon.png"),
  cancel: require("../assets/images/cancel.png"),
  favicon: require("../assets/images/favicon.png"),
  icon: require("../assets/images/icon.png"),
  leisure: require("../assets/images/leisure.png"),
  magnifer: require("../assets/images/Magnifer.png"),
  relax: require("../assets/images/relax.png"),
  running: require("../assets/images/running.png"),
  speed: require("../assets/images/speed.png"),
  splash: require("../assets/images/splash.png"),
  backArrow: require("../assets/images/backArrow.png"),
  share: require("../assets/images/upload.png"),
  heart: require("../assets/images/HEART.png"),
  camera1: require("../assets/images/camera1.png"),
  docEdit: require("../assets/images/docEdit.png"),
  del: require("../assets/images/del.png"),
  stripe: require("../assets/images/stripe.png"),
  paypal: require("../assets/images/paypal.png"),
  tick: require("../assets/images/tick.png"),
  zumba: require("../assets/images/zumba.png"),
  clockNew: require("../assets/images/clockNew.png"),
  loc: require("../assets/images/loc.png"),
  checkNew: require("../assets/images/checkNew.png"),
  userGirl: require("../assets/images/userGirl.png"),
  closeButton: require("../assets/images/closeButton.png"),
  call: require("../assets/images/call.png"),
  msg: require("../assets/images/msg.png"),
  timeNew: require("../assets/images/timeNew.png"),
  locNew: require("../assets/images/locNew.png"),
  calNew: require("../assets/images/calNew.png"),
  arrDown: require("../assets/images/arrDown.png"),
  delCircle: require("../assets/images/delCircle.png"),
  send: require("../assets/images/send.png"),
  locc: require("../assets/images/locc.png"),
  timee: require("../assets/images/timee.png"),
  time3:require("../assets/images/time3.png"),
  location4:require("../assets/images/location4.png"),
  arrNew: require("../assets/images/arrNew.png"),
  arrNew1: require("../assets/images/arrNew1.png"),
  maps: require("../assets/images/maps.png"),
  maps1: require("../assets/images/maps1.png"),
  blackLoc: require("../assets/images/blackLoc.png"),
  ball: require("../assets/images/ball.png"),
  shield: require("../assets/images/shield.png"),
  clockB: require("../assets/images/clockB.png"),
  pencil: require("../assets/images/pencil.png"),
  bulb: require("../assets/images/bulb.png"),
  clock1:require("../assets/images/clock1.png"),
  location3:require("../assets/images/location3.png"),
  profile3:require("../assets/images/profile2.png"),
  term:require("../assets/images/page.png"),
  payment:require("../assets/images/card.png"),
  transaction:require("../assets/images/list.png"),
  refer:require("../assets/images/gift.png"),
  star:require("../assets/images/star.png"),
  settings:require("../assets/images/settings.png"),
  stockImage1:require("../assets/images/stockImage1.jpg"),
  stockImage2:require("../assets/images/stockImage2.jpg"),
  stockImage3:require("../assets/images/stockImage3.jpg"),
  stockImage4:require("../assets/images/stockImage4.jpg"),
  stockImage5:require("../assets/images/stockImage5.jpg"),
  arrow1:require("../assets/images/arrow-tr.png"),
  arrow2:require("../assets/images/arrow-bl.png"),
  applePay:require("../assets/images/ApplePay.png"),
  paypal1:require("../assets/images/PayPal1.png"),
  Visa:require("../assets/images/Visa.png"),
  Mastercard:require("../assets/images/Mastercard.png"),
  bank:require("../assets/images/bank.png"),
  creditCard:require("../assets/images/credit-card.png"),
  card1:require("../assets/images/card1.png"),
  checkbox:require("../assets/images/checkbox.png"),
  coupon:require("../assets/images/promotion.png"),
  info:require("../assets/images/info.png"),
  Discover:require("../assets/images/Discover.png"),
  Amex:require("../assets/images/Amex.png"),
  gradient:require("../assets/images/gradient.png"),
  noevent:require("../assets/images/noevent.png"),
  info1:require("../assets/images/info1.png"),
  calendar1:require("../assets/images/calendar1.png"),
  share1:require("../assets/images/share1.png"),
  barcode:require("../assets/images/barcode.png"),
  pass:require("../assets/images/security-pass.png"),
  camea:require("../assets/images/camea.png"),
  camera2:require("../assets/images/camera2.png"),
  prohibition:require("../assets/images/prohibition.png"),
  other:require("../assets/images/other.png"),
  non_binary:require("../assets/images/non-binary.png"),
  male:require("../assets/images/male.png"),
  female:require("../assets/images/female.png"),
  privacy:require("../assets/images/privacy.png"),
  noResults:require("../assets/images/noResults.png"),
  checkCircle: require('../assets/images/Check-Circle.png')
};
