export const BASE_URL = "https://api.cofitapp.com";
export const REGISTER = "/api/register";
export const GET_USER_DETAILS = "/api/get-user-details";
export const UPDATE_USER_DETAILS="/api/update-user";
export const GET_EVENTS_BY_ID="/api/event-detail";
export const ADD_EVENTS="/api/add-event";
export const EDIT_EVENTS="/api/edit-event";
export const GET_USER_EVENTS="/api/event-listing";
export const ADD_EVENT_IMAGE="/api/add-event-image"