export const BASE_URL = "https://api.cofitapp.com";
export const REGISTER = "/api/register";
export const GET_EVENTS = "/api/get-event"
export const GET_USER_DETAILS = "/api/get-user-details";
export const UPDATE_USER_DETAILS="/api/update-user";
export const GET_EVENTS_BY_ID="/api/event-detail";
export const ADD_EVENTS="/api/add-event";
export const ADD_EVENTS_NEW="/api/add-events";
export const EDIT_EVENTS="/api/edit-event";
export const GET_USER_EVENTS="/api/event-listing";
export const ADD_EVENT_IMAGE="/api/add-event-image";
export const MY_EVENTS='/api/get-event';
export const EVENT_CATEGORIES='/api/get-event-category'
export const GET_CARDS='/api/get-all-cards'
export const ADD_PAYMENT_METHODS="/api/payment-methods"
export const ATTACH_PAYMENT_METHODS="/api/attach-customer-payment"
export const REMOVE_PAYMENT_METHODS="/api/detach-customer-payment"
export const CREATE_PAYMENT_INTENT="/api/create-payment-intent"
export const CREATE_PAYMENT_INTENT_NEW="/api/create-payment-intents"
export const CONFIRM_PAYMENT_INTENT="/api/payment-intents/confirm"
export const CREATE_ACCOUNT_LINK="/api/create-account-link"
export const CHECK_TICKET_AVAILABILITY='/api/fetch-event-ticket-availability'
export const BOOK_EVENT = "/api/book-event"
export const GET_BOOKED_EVENT = '/api/booked-event-listing'
export const RETRIVE_STRIPE_ACCOUNT='/api/retrieve-account'
export const MANAGE_EVENT = '/api/manage-event'
export const GET_ALL_CITIES='/api/get-all-cities'
export const TRANSACTIONS = '/api/transactions'
export const GET_PROMO_CODES = '/api/promo-codes'
export const SIGN_UP = '/api/signup'
export const ADD_PROFILE = '/api/add-profile'
export const LOGIN = '/api/login'
export const GOOGLE_LOGIN = '/api/google-login'
export const APPLE_LOGIN = '/api/apple-login'
export const DELETE_ACCOUNT = '/api/delete-account'
export const FORGOT_PASSWORD = '/api/send-reset-link'
export const PRIVACY_POLICY = '/api/privacy-policy'
export const TERM_SERVICE = '/api/terms'